### ISSUE TITLE
Cannot install on python 3.6

### ISSUE THREAD

**Issue by yggdr** [joaduo/rel_imp#1]
`pip3.6 install --user rel_imp
Collecting rel_imp
  Using cached https://files.pythonhosted.org/packages/ec/25/a2889c7d1822d96548b3809559dc94d614c9fc5e5332c19b892a0cb4efce/rel_imp-0.2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nwwq3s82/rel-imp/setup.py", line 16, in <module>
        long_description=long_description(),
      File "/tmp/pip-build-nwwq3s82/rel-imp/setup.py", line 9, in long_description
        return unicode(f.read())
    NameError: name 'unicode' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nwwq3s82/rel-imp/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by joaduo** [comment]
Fixed in 0.2.7
You should be able to install it from pip.
Thanks for the report!
